### ISSUE TITLE
Error updating

### ISSUE THREAD

**Issue by prschopf** [splitbrain/dokuwiki-plugin-upgrade#187]
I tried to update my wiki today and I got this message:

DokuWiki rc2020-06-01 "Hogfather" is available for download.
You're currently running DokuWiki Release 2018-04-22c "Greebo".
It's not clear how old your currently running version is, manual upgrade is recommended.

Is it a bug?

**Comment by bradbulger** [comment]
changing the version pattern match in admin.php from (?:rc) to (?:rc|) got past this issue for me

**Comment by prschopf** [comment]
it solved here as well. Thank you!

**Comment by cvoltz** [comment]
Even with the patch, I still see the same problem. I verified that I had the updated version you just made available:
```php
        if(!preg_match('/(^| )(?:rc)(\d\d\d\d-\d\d-\d\d[a-z]*)( |$)/i', $tgzversion, $m)) {
            $this->_warn($this->getLang('vs_tgzno'));
            $ok            = false;
            $tgzversionnum = 0;
        } else {
            $tgzversionnum = $m[2];
            self::_say($this->getLang('vs_tgz'), $tgzversion);
        }

        // get the current version
        $version = getVersion();
        if(!preg_match('/(^| )(?:rc)(\d\d\d\d-\d\d-\d\d[a-z]*)( |$)/i', $version, $m)) {
            $versionnum = 0;
        } else {
            $versionnum = $m[2];
        }
 ```

**Comment by Miro-Collas** [comment]
I get the same error when trying to update. Given the post above, I have not tried to edit any files yet. Will wait to see if there are developments.

**Comment by splitbrain** [comment]
should be fixed with d96773ca73cfa2849b12aaabba18ce7a439ca535

**Comment by bduplanty** [comment]
That solved it for me.  Thank you!

**Comment by Miro-Collas** [comment]
> should be fixed with [d96773c](https://github.com/splitbrain/dokuwiki-plugin-upgrade/commit/d96773ca73cfa2849b12aaabba18ce7a439ca535)

Yes thanks, perfect! :-)

**Comment by Marx1st** [comment]
> Using plugin upgrade latest version, Im getting this "error":
> 
> DokuWiki rc-2020-06-09 "Hogfather" RC3 is available for download.
> You're currently running DokuWiki Release rc-2020-06-09 "Hogfather" RC3.
> 
> And "Continue" button is available. Is it right?

It doesn't look so. Especially as my admin.php doesn't look like the one mentioned above... somethings very wrong here...

**Comment by prschopf** [comment]
> > Using plugin upgrade latest version, Im getting this "error":
> > DokuWiki rc-2020-06-09 "Hogfather" RC3 is available for download.
> > You're currently running DokuWiki Release rc-2020-06-09 "Hogfather" RC3.
> > And "Continue" button is available. Is it right?
> 
> It doesn't look so. Especially as my admin.php doesn't look like the one mentioned above... somethings very wrong here...

Yes, mine is different too, in latest version of this plugin. I dont know how to fix it.
